GH-81: Migrate to `fluid-lint-all`, fix linting errors, adjust rules (resolves #81).
fluid-lab/gamepad-navigator pull request #82
Opened 2021-01-13 15:49 UTC by the-t-in-rtf

Although we use `Grunt` for other things in this package, moving forward the linting infrastructure used within the community is migrating away from `Grunt`.  This pull migrates this package to use the new tool, and fixing the minor linting errors that result from the new CSS linting added in recent versions.

@dmahajan980, this should be merged once there is a full release, but I've flagged it for your review in the mean time.

2021-01-13 15:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/fluid-lab/gamepad-navigator?pullRequest=82) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/fluid-lab/gamepad-navigator?pullRequest=82) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/fluid-lab/gamepad-navigator?pullRequest=82) it.</sub>

2021-01-14 12:51 UTC, dmahajan980 requested changes
@the-t-in-rtf, this looks solid. You should also update the "lint command" in the [Publishing doc](https://github.com/fluid-lab/gamepad-navigator/blob/main/docs/PUBLISHING.md) (step 1.iii.a). Other than that, everything seems fine to me.

2021-01-15 18:43 UTC, dmahajan980 approved these changes

2021-01-19 10:30 UTC, merged

2021-01-19 10:32 UTC, the-t-in-rtf commented
@dmahajan980, I have merged the pull now that the released version of `fluid-lint-all` is available.  I don't think we need to publish a new release as the code changes were minor CSS linting fixes and do not change any functionality.